### ISSUE TITLE
Error using the includes query param

### ISSUE THREAD

**Issue by stuliston** [hooroo/http_api_tools#7]
I was messing around with the [Reservations endpoint](https://qantas.staging.jqdev.net/api/v1/reservations?app_key=LOLREDACTED&app_secret_key=LOLREDACTED) on Hotels and got the following error in Airbrake:

[NoMethodError: undefined method `as_sideloaded_hash' for PropertySerializer:0x007fd65f5961a8](https://jetstar.airbrake.io/projects/38761/groups/1500294024432884014/notices/1500294024432884013)

The `meta` response suggests that those entities are includable:

```json
"meta": {
"type": "reservation",
"root_key": "reservations",
"offset": 0,
"limit": 10,
"sort_by": "id",
"sort_dir": "DESC",
"count": 10,
"total": 740314,
"includable": "offer,property",
"included": ""
},
```

The URI was:

`/api/v1/reservations?include=offer,property&app_key=LOLREDACTED&app_secret_key=LOLREDACTED`

I'm investigating now.

**Comment by mikemortimer** [comment]
💩

**Comment by pmoran** [comment]
The problem is there is no method called as_sideloaded_hash defined. I hope
that helps.


Peter Moran
0407 441030

**Comment by stuliston** [comment]
Two very helpful comments, gentlemen! :grinning: 

Turns out the issue was that Hotels uses the old gem DSL and needs to be updated. I'm closing this and dealing with it in that repo - which has the benefit of being private and therefore free from :trollface:!

**Comment by pmoran** [comment]
You're aware I now have your app_secret_key?


Peter Moran
0407 441030

**Comment by stuliston** [comment]
Those were staging deets - but the guys took great pleasure in redacting them and issuing me with a warning ;-)
